import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const inter = Inter({
  subsets:['latin'],
  variable: "--font-inter",
})

const playfair = Playfair_Display({
  subsets:['latin'],
  variable: "--font-playfair", 
})





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-inter antialiased min-h-[100vh] flex flex-col px-5` }
      >
        <Header />
        <main className="flex-1 ">
          <div className="container max-w-[1240px] mx-auto">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
